// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIv7NbiPn0sbNLkDznB1sO7FmIVe8cSM',
    appId: '1:59930507468:web:662a30e513366410f0aa69',
    messagingSenderId: '59930507468',
    projectId: 'djlog-2603b',
    authDomain: 'djlog-2603b.firebaseapp.com',
    storageBucket: 'djlog-2603b.firebasestorage.app',
    measurementId: 'G-C3C3GV9050',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCte0XKtwrUIVpLqyEU_Ea_efvYq3YScqE',
    appId: '1:59930507468:android:41d46ae1ddf01222f0aa69',
    messagingSenderId: '59930507468',
    projectId: 'djlog-2603b',
    storageBucket: 'djlog-2603b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WsnE8QtyX1Io_O955mAih8GWOCKM5eM',
    appId: '1:59930507468:ios:cbc5713af41b36cff0aa69',
    messagingSenderId: '59930507468',
    projectId: 'djlog-2603b',
    storageBucket: 'djlog-2603b.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WsnE8QtyX1Io_O955mAih8GWOCKM5eM',
    appId: '1:59930507468:ios:cbc5713af41b36cff0aa69',
    messagingSenderId: '59930507468',
    projectId: 'djlog-2603b',
    storageBucket: 'djlog-2603b.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIIv7NbiPn0sbNLkDznB1sO7FmIVe8cSM',
    appId: '1:59930507468:web:ae9cb68cbdfb85b8f0aa69',
    messagingSenderId: '59930507468',
    projectId: 'djlog-2603b',
    authDomain: 'djlog-2603b.firebaseapp.com',
    storageBucket: 'djlog-2603b.firebasestorage.app',
    measurementId: 'G-K9E36ZT19C',
  );
}
